// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseEmptyList: typeof import('./src/components/BaseEmptyList.vue')['default']
    CharacterListItem: typeof import('./src/components/character/CharacterListItem.vue')['default']
    CharacterListView: typeof import('./src/components/character/CharacterListView.vue')['default']
    CharacterListViewPlaceholder: typeof import('./src/components/character/CharacterListViewPlaceholder.vue')['default']
    CharacterView: typeof import('./src/components/character/CharacterView.vue')['default']
    FilterDropdown: typeof import('./src/components/FilterDropdown.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search/SearchBar.vue')['default']
    SearchBarHintsPlaceholder: typeof import('./src/components/search/SearchBarHintsPlaceholder.vue')['default']
    TheBreadcrumb: typeof import('./src/components/TheBreadcrumb.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
  }
}

export {}
